Fix #9：会計局の全体総括を執筆した
ritscc/soukai-2020-1 pull request #45
Opened 2020-09-20 14:46 UTC by Koyanagi-Masafumi

2020-09-21 18:11 UTC, 3to5thpower approved these changes
全体的に記述量が少なく、前期の活動内容とか状況が伝わりにくいように思われます。
特に会費徴収ができなかった件や学友会費案件(こちらは今の文章でも説明されていますが)は詳しく状況を記述して後から参照できるようにしておくのが良いと思うので、もし余裕があれば追記などをした方が良いかもしれません。

2020-09-22 00:39 UTC, hirotta requested changes
金額表記は全角カンマでなく半角カンマを使ってください

2020-09-22 01:00 UTC, hirotta approved these changes

2020-09-22 02:22 UTC, hirotta commented
19年度後期総会で特別負担金が承認されてるので，新歓企画中止により特別負担金を徴収しないことも書いておいた方がいいかも

2020-09-22 06:49 UTC, hirotta approved these changes

2020-09-22 09:02 UTC, thetaleisalsowhite commented on src/soukatsu/kaikei/01_zentai.tex
> +2020年度春学期はほとんど支出がなく，決算を作成していないため公開しなかった．
一般に決算は0でない限り行われるべき物である為、欲を言えば"ほとんどない"を根拠にするべきでないと思います。完全に支出0だったか、別の根拠の提示が望ましいと思います。

2020-09-22 12:15 UTC, takion88 approved these changes

2020-09-22 12:19 UTC, Hara-Yuma approved these changes

2020-09-22 16:11 UTC, kanon-k4 requested changes

2020-09-22 16:11 UTC, kanon-k4 commented on src/soukatsu/kaikei/01_zentai.tex
> +承認されていなかった理由については学術本部が，コロナウイルスの影響でセントラルアクトオフィスが閉鎖されており，2020年度春学期は調査ができないとしており，現段階では詳しく記述することができない．
承認されていなかった理由について学術本部に問い合わせた所，コロナウイルスの影響でセントラルアクトオフィスが閉鎖されているため，2020年度春学期中は調査を行わないと回答があり，現段階では詳しく記述することが不可能である．

2020-09-22 16:12 UTC, kanon-k4 requested changes

2020-09-22 16:12 UTC, kanon-k4 commented on src/soukatsu/kaikei/01_zentai.tex
> +承認されていなかった理由については学術本部が，コロナウイルスの影響でセントラルアクトオフィスが閉鎖されており，2020年度春学期は調査ができないとしており，現段階では詳しく記述することができない．
```suggestion
承認されていなかった理由について学術本部に問い合わせた所，コロナウイルスの影響でセントラルアクトオフィスが閉鎖されているため，2020年度春学期中は調査を行わないと回答があり，現段階では詳しく記述することが不可能である．
```

2020-09-23 00:57 UTC, merged