Fix #17 シス管勉強会総括。宇佐
ritscc/soukai-2020-1 pull request #54
Opened 2020-09-20 18:15 UTC by thetaleisalsowhite

2020-09-21 19:13 UTC, 3to5thpower reviewed
勉強会総括のブランチで関係のないファイルを編集しないでください…

あと勉強会方針が勉強会総括と全く同じ内容なのはどうしててですか？

2020-09-21 19:13 UTC, 3to5thpower commented on src/houshin/2kai.tex
> +\subsubsection*{進捗を生む活動}
「進捗を生む」は文書に適さない気はしますね…
単にRCCの活動を頑張ろうってなら「学習・研究活動」などでもよいと思います

2020-09-21 19:13 UTC, 3to5thpower commented on src/soukatsu/system/03_study.tex
> +ubsection*{勉強会総括}
\subsectionが一部消えてます

2020-09-22 11:58 UTC, Hara-Yuma reviewed
適度な改行が欲しいです．

2020-09-22 11:58 UTC, Hara-Yuma commented on src/houshin/2kai.tex
> +2020年度春学期の活動では，LTの遅延など，\firstGrade{}の模範としてふさわしくない行動をしない様にする．や学園祭の展示企画，Advent Calendarの締め切りなどを守るように徹底しつつ，各人の活動を行っていくものとする．
```suggestion
2020年度春学期の活動では，LTの遅延など，\firstGrade{}の模範としてふさわしくない行動をしないようにする．や学園祭の展示企画，Advent Calendarの締め切りなどを守るように徹底しつつ，各人の活動を行っていくものとする．
```

2020-09-22 11:58 UTC, Hara-Yuma commented on src/houshin/2kai.tex
> +何かしらの形で示せる成果を秋学期末までに制作する．通年で行われたプロジェクト活動の目標を意識的に達成するよう心掛ける．
何かしらの形という文言は避けるべきだと思います．
```suggestion
2020年度秋学期中に，成果物を作成する．
通年で行われたプロジェクト活動の目標を意識的に達成するよう心掛ける．
```

2020-09-22 12:00 UTC, Hara-Yuma commented
てか，関係ないファイルの変更も反映されてませんかこれ

2020-09-22 12:04 UTC, flaireclair requested changes

2020-09-22 12:04 UTC, flaireclair commented on src/houshin/2kai.tex
> +COVID-19の感染対策を十分に意識したうえで外部の学習機会を積極的に持つように行動する．獲得した知識は定例会議内のLTなどで積極的に発信するようにする．
関係ないファイルなのでプルリクから排除

2020-09-22 12:04 UTC, flaireclair commented on src/houshin/system/03_study.tex
> +\end{itemize}
関係ないファイルなのでプルリクから排除

2020-09-22 16:27 UTC, kanon-k4 commented on src/soukatsu/system/03_study.tex
> +当日の勉強会進行の点でも古参会員の機転とノウハウに依存する場面があった．主要回生である\secondgrade{}のみでの運営が望ましい．
```suggestion
当日の勉強会進行の点でも古参会員の機転とノウハウに依存する場面があった．主要回生である\secondGrade{}のみでの運営が望ましい．
```

2020-09-22 18:08 UTC, merged