Fix#63:会計局_方針文章の記述
ritscc/soukai-2020-1 pull request #66
Opened 2020-09-21 03:16 UTC by Tanabe-616

2020-09-21 20:36 UTC, 3to5thpower requested changes

2020-09-21 20:36 UTC, 3to5thpower commented on src/houshin/kaikei/01_zentai.tex
> +ハッカソンは技術力の向上及び会員間の交流に役立つものであるため，2021年度も夏期と冬期に1回ずつ行う．
上回生・OB・企業の方の項にハッカソンの概要説明があるのは不自然ですね
企画書などにのっとり詳しい説明を書くのは基本的には良いことだと思いますが記述する場所および記法は
文章として適切なものにしてください

2020-09-22 11:51 UTC, flaireclair requested changes

2020-09-22 11:51 UTC, flaireclair commented on src/houshin/kaikei/01_zentai.tex
> +
ハッカソンの企画書にしか見えないので総会文書に適する記述をしてください

2020-09-22 12:20 UTC, Tanabe-616 commented on src/houshin/kaikei/01_zentai.tex
> +
直してみたんですがこれでどうでしょうか？

2020-09-22 12:20 UTC, Tanabe-616 commented on src/houshin/kaikei/01_zentai.tex
> +作成した引き継ぎ文書に随時変更と修正を加える．
修正しました

2020-09-22 12:21 UTC, Tanabe-616 commented on src/houshin/kaikei/01_zentai.tex
> +コロナが収束し，活動が再開された場合は購入申請を受け付ける．
修正しました

2020-09-22 12:38 UTC, Tanabe-616 commented on src/houshin/kaikei/01_zentai.tex
> +ハッカソンは技術力の向上及び会員間の交流に役立つものであるため，2021年度も夏期と冬期に1回ずつ行う．
すみません、修正しました

2020-09-22 12:54 UTC, flaireclair commented on src/houshin/kaikei/01_zentai.tex
> +
https://github.com/ritscc/soukai-2020-1/pull/66/commits/aa24c19066a43fb9dbcaf2a3e31ff5ed4eb126ce

2020-09-22 13:02 UTC, flaireclair commented on src/houshin/kaikei/01_zentai.tex
> +め，開催日までの時間などを鑑みて上回生会議で議論し，参加の許可を決定する．
開催しないのに行う予定とはいかに
あと無駄に文章を長くするのはあまり好ましくない
というより本当にこれで開催できるんですか

2020-09-22 18:54 UTC, greenlaver commented on src/houshin/kaikei/01_zentai.tex
> +グループ分けは，担当者が行い，開催 1 週間前までにテーマと共に参加者に通知する．そこから
> 開催 1 週間前

数字の前後に謎のスペース入ってるんで消しといてくださいな

2020-09-22 18:58 UTC, greenlaver commented on src/houshin/kaikei/01_zentai.tex
> +グループ分けは，担当者が行い，開催 1 週間前までにテーマと共に参加者に通知する．そこから
同上
https://github.com/ritscc/soukai-2020-1/blob/aa24c19066a43fb9dbcaf2a3e31ff5ed4eb126ce/src/houshin/kaikei/01_zentai.tex#L50
https://github.com/ritscc/soukai-2020-1/blob/aa24c19066a43fb9dbcaf2a3e31ff5ed4eb126ce/src/houshin/kaikei/01_zentai.tex#L60-L61
https://github.com/ritscc/soukai-2020-1/blob/aa24c19066a43fb9dbcaf2a3e31ff5ed4eb126ce/src/houshin/kaikei/01_zentai.tex#L63

2020-09-22 19:10 UTC, greenlaver requested changes

2020-09-22 19:10 UTC, greenlaver commented on src/houshin/kaikei/01_zentai.tex
> +特別議案が通った後に，4500円を口座振込で徴収する．(総会文書に書く前に確認)
https://github.com/ritscc/soukai-2020-1/blob/aa24c19066a43fb9dbcaf2a3e31ff5ed4eb126ce/src/houshin/kaikei/01_zentai.tex#L28

> (総会文書に書く前に確認)

_This is 総会文書_ なんですがそれは...

2020-09-22 19:15 UTC, greenlaver reviewed
謎の空白がある部分について修正案を投げておきました

2020-09-22 19:15 UTC, greenlaver commented on src/houshin/kaikei/01_zentai.tex
> +ハッカソンは技術力の向上及び会員間の交流に役立つものであるため，2020年度秋学期も冬期休暇中に 1 回
```suggestion
ハッカソンは技術力の向上及び会員間の交流に役立つものであるため，2020年度秋学期も冬期休暇中に1回
```

2020-09-22 19:15 UTC, greenlaver commented on src/houshin/kaikei/01_zentai.tex
> +グループ分けは，担当者が行い，開催 1 週間前までにテーマと共に参加者に通知する．そこから
```suggestion
グループ分けは，担当者が行い，開催1週間前までにテーマと共に参加者に通知する．そこから
```

2020-09-22 19:15 UTC, greenlaver commented on src/houshin/kaikei/01_zentai.tex
> +発表に関しては，所要時間は 1~2 時間とし，一班あたりの上限時間は 20 分程度とする．成果物
```suggestion
発表に関しては，所要時間は1~2時間とし，一班あたりの上限時間は20分程度とする．成果物
```

2020-09-22 19:15 UTC, greenlaver commented on src/houshin/kaikei/01_zentai.tex
> +成果発表を行う．場所はエポック立命 21 で行い，期間は 3 日間とする．
```suggestion
成果発表を行う．場所はエポック立命21で行い，期間は3日間とする．
```

2020-09-22 19:15 UTC, greenlaver commented on src/houshin/kaikei/01_zentai.tex
> +本会の OB など，学内の方が訪問してきた場合は特に拒まず，活動に参加させる．しかし，他大
```suggestion
本会のOBなど，学内の方が訪問してきた場合は特に拒まず，活動に参加させる．しかし，他大
```

2020-09-22 22:19 UTC, Tanabe-616 commented on src/houshin/kaikei/01_zentai.tex
> +め，開催日までの時間などを鑑みて上回生会議で議論し，参加の許可を決定する．
すみません、開催が未定なので50行目と『次回の目標』を削除しました。

2020-09-23 01:04 UTC, merged