Fix #28 : LT総括を作成
ritscc/soukai-2020-1 pull request #74
Opened 2020-09-21 09:59 UTC by fukada6280

2020-09-21 20:27 UTC, flaireclair requested changes

2020-09-21 20:27 UTC, flaireclair commented on src/soukatsu/kensui/03_LT.tex
>  %\writtenBy{\kensuiStaff}{深田}{紘希}
どちらかのコメントアウトを消してください

2020-09-21 20:27 UTC, flaireclair commented on src/soukatsu/kensui/03_LT.tex
> +\secondGrade{}以上を中心に活発にLTを行うことができた．
1回生総括と齟齬が生まれているので、もしこれが強制LTに関することを記しているのであれば、飛込LTに1回生が積極的に参加していたことも記しておいた方がいいかも

2020-09-21 20:33 UTC, 3to5thpower approved these changes

2020-09-22 09:29 UTC, thetaleisalsowhite approved these changes

2020-09-22 17:10 UTC, merged