Fix #25: 3回生方針を執筆
ritscc/soukai-2020-1 pull request #77
Opened 2020-09-21 11:41 UTC by Sayori13

2020-09-21 20:20 UTC, flaireclair requested changes

2020-09-21 20:20 UTC, flaireclair commented on src/houshin/3kai.tex
> +　1点目の下回生のサポートついて，春学期に引き続き過干渉しないが下回生が円滑に業務を全うできるような補助を心がける．
`春学期`
2020年度春学期

2020-09-21 20:20 UTC, flaireclair commented on src/houshin/3kai.tex
> +また，2020年度は対面での活動がなく交流する機会が少なかったため，活動において\firstGrade{}には特に気を配る．
`2020年度は対面での活動がなく交流する機会が少なかったため，`
「2020年度秋学期は2020年度春学期と同様に対面での活動がなく交流する機会が少なくなると予想されるため，」かな

2020-09-21 20:42 UTC, 3to5thpower approved these changes

2020-09-22 09:31 UTC, thetaleisalsowhite approved these changes

2020-09-22 12:14 UTC, takion88 approved these changes

2020-09-22 17:13 UTC, merged