シス管局会議総括を執筆
ritscc/soukai-2020-1 pull request #83
Opened 2020-09-21 13:18 UTC by yuyueuph

2020-09-21 20:09 UTC, flaireclair commented on src/soukatsu/system/02_kyokukaigi.tex
> +しかし，一部参加率が著しく低い局員が数名いた．
原因などが欲しいですね

2020-09-21 20:09 UTC, flaireclair commented on src/soukatsu/system/02_kyokukaigi.tex
> +当初，1回の会議につき，1時限(90分)以上の時間を確保することを目標としてたが十分に達成できたと考える．
`1時限(90分)`
90分で十分

2020-09-21 20:55 UTC, 3to5thpower requested changes

2020-09-21 20:55 UTC, 3to5thpower commented on src/soukatsu/system/02_kyokukaigi.tex
> +2020年度はDiscodeを用いたリモート会議を行った．
```suggestion
2020年度はDiscordを用いたリモート会議を行った．
```

2020-09-22 17:18 UTC, 3to5thpower commented on src/soukatsu/system/02_kyokukaigi.tex
> +当初，1回の会議につき，1時限(90分)以上の時間を確保することを目標としてたが十分に達成できたと考える．
```suggestion
当初，1回の会議につき，90分以上の時間を確保することを目標としてたが十分に達成できたと考える．
```

2020-09-22 17:24 UTC, merged