シス管局会議方針を執筆
ritscc/soukai-2020-1 pull request #85
Opened 2020-09-21 14:07 UTC by yuyueuph

2020-09-21 20:04 UTC, flaireclair requested changes

2020-09-21 20:04 UTC, flaireclair commented on src/houshin/system/02_kyokukaigi.tex
> +春学期同様に，秋学期も週1回開催する．
春学期 -> 2020年度春学期
秋学期 -> 2020年度秋学期

2020-09-21 21:07 UTC, 3to5thpower approved these changes

2020-09-22 10:06 UTC, thetaleisalsowhite approved these changes

2020-09-22 17:21 UTC, merged