Fix #6 : １回生総括を執筆
ritscc/soukai-2020-1 pull request #86
Opened 2020-09-21 14:09 UTC by Ran350

2020-09-21 20:00 UTC, flaireclair commented on src/soukatsu/1kai.tex
> +そんな中でも，新歓交流会では，普段交流の少ない会員間での親睦を深めることができたと考えられる．
そんな中 -> そのような中
あと句点が多い印象

2020-09-21 20:02 UTC, flaireclair requested changes

2020-09-21 20:02 UTC, flaireclair commented on src/soukatsu/1kai.tex
> +そんな中でも，新歓交流会では，普段交流の少ない会員間での親睦を深めることができたと考えられる．
`普段交流の少ない会員間での親睦を深めることができたと考えられる．`
例年通り交流ができた -> その旨を明記
例年よりも交流ができた -> なぜそのようになったのか明記

2020-09-21 20:02 UTC, flaireclair commented on src/soukatsu/1kai.tex
> +そんな中でも，新歓交流会では，普段交流の少ない会員間での親睦を深めることができたと考えられる．
そんな中 -> そのような中

2020-09-21 20:02 UTC, flaireclair commented on src/soukatsu/1kai.tex
> +プロジェクトやWelcomeゼミ，git勉強会などでの活動を通して向上したと考えられる．
あと全体的に句点が多い印象

2020-09-21 21:00 UTC, 3to5thpower requested changes

2020-09-21 21:00 UTC, 3to5thpower commented on src/soukatsu/1kai.tex
> +プロジェクトやWelcomeゼミ，git勉強会などでの活動を通して向上したと考えられる．
ソフトウェア名としては"Git"の表記が正しいっぽい(?)のでGit勉強会と書いた方がいいかもしれません

2020-09-22 11:08 UTC, Ran350 commented on src/soukatsu/1kai.tex
> +プロジェクトやWelcomeゼミ，git勉強会などでの活動を通して向上したと考えられる．
”Git勉強会”に修正致しました。

2020-09-22 11:08 UTC, Ran350 commented on src/soukatsu/1kai.tex
> +また，平常活動でも，TwitterやDiscodeなどSNSを通して，
”Discord”に修正致しました。

2020-09-22 11:09 UTC, Ran350 commented on src/soukatsu/1kai.tex
> +そんな中でも，新歓交流会では，普段交流の少ない会員間での親睦を深めることができたと考えられる．
”そのような中”に修正致しました。

2020-09-22 11:10 UTC, Ran350 commented on src/soukatsu/1kai.tex
> +プロジェクトやWelcomeゼミ，git勉強会などでの活動を通して向上したと考えられる．
不要な句点を削除致しました。

2020-09-22 17:22 UTC, merged