Update 1kai.tex
ritscc/soukai-2020-1 pull request #90
Opened 2020-09-21 15:11 UTC by mizugoro

2020-09-21 18:35 UTC, 3to5thpower approved these changes
問題は特にないと思いますが要らないプルリクは消しといてください
unagiに怒られたら同じブランチで修正してpushすればわざわざ作り直さなくていいので…

2020-09-21 19:49 UTC, flaireclair commented on src/houshin/1kai.tex
> +「親睦を深める」「規律ある行動」「自己発信力の向上」「技術力の向上」「運営に意識を向ける」,これらを{\firstGrade{}}2020年度秋学期の活動方針とする.プロジェクト活動を通して親睦を深める.ネットリテラシーを身に着けることで規律ある行動を目指す.アドベントカレンダーやLTを通じて自己発信力を向上させる.プロジェクト活動だけでなく自主的な活動を通じて技術力の向上を目指す.局配属を通し
{\firstGrade{}} これって {一回生} にはならないんですよね？
であれば大丈夫です。

2020-09-21 19:50 UTC, flaireclair approved these changes

2020-09-21 21:18 UTC, 3to5thpower requested changes
句読点は全角の，と．なのでそれは修正しといてください

2020-09-22 17:29 UTC, kanon-k4 approved these changes

2020-09-22 17:36 UTC, merged