シス管引き継ぎ方針の執筆
ritscc/soukai-2020-1 pull request #91
Opened 2020-09-21 15:14 UTC by yuyueuph

2020-09-21 19:47 UTC, flaireclair approved these changes

2020-09-21 21:19 UTC, 3to5thpower requested changes

2020-09-21 21:19 UTC, 3to5thpower commented on src/houshin/system/05_hikitugi.tex
> +システム管理に関する業務は引き続き上回生の支援の元で行っていく．
```suggestion
システム管理に関する業務は引き続き上回生の支援の下で行っていく．
```

2020-09-22 17:36 UTC, kanon-k4 approved these changes

2020-09-22 17:41 UTC, merged