websoukatsu
ritscc/soukai-2020-1 pull request #92
Opened 2020-09-21 15:36 UTC by mizugoro

2020-09-21 19:43 UTC, flaireclair commented on src/soukatsu/syogai/04_web.tex
> +
事実を述べるだけでは総会文書の意味はないのでは

2020-09-21 21:19 UTC, 3to5thpower requested changes
句読点は全角

2020-09-22 14:02 UTC, Hara-Yuma requested changes

2020-09-22 14:02 UTC, Hara-Yuma commented on src/soukatsu/syogai/04_web.tex
> +例年通り新入生歓迎サイトの制作を行った.新入生歓迎サイトには本会についての情報や新入生歓迎のイベントの情報が載せられた.
以下のようなフォーマットで，目的や結果を書いてもらえば十分な内容になると思います．
```suggestion
2020年度春学期には，例年通り新入生歓迎サイトの制作を行った.

新入生歓迎サイトには，○○ことを目的として，本会についての情報や新入生歓迎のイベントの情報を掲載した．
これによって，○○だったと考えられる．
```

2020-09-22 17:56 UTC, merged