2回生総括の執筆
ritscc/soukai-2020-1 pull request #93
Opened 2020-09-21 16:13 UTC by yuyueuph

2020-09-21 19:40 UTC, flaireclair approved these changes

2020-09-21 21:24 UTC, 3to5thpower requested changes

2020-09-21 21:24 UTC, 3to5thpower commented on src/soukatsu/2kai.tex
> +\subsection*{\secondGrade{}総括
これ閉じ括弧消えてるのでは？

2020-09-21 21:24 UTC, 3to5thpower commented on src/soukatsu/2kai.tex
> +の4点あった．
```suggestion
の4点であった．
```

2020-09-21 21:24 UTC, 3to5thpower commented on src/soukatsu/2kai.tex
> +しかしその中でもオンラインでの勉強会やLT会に参加する\secondGrade{}もおり，
「おる」は謙譲語なので丁寧語としては使えません
単に「見られ、」などで良さそう

2020-09-22 09:52 UTC, thetaleisalsowhite approved these changes

2020-09-22 17:27 UTC, kanon-k4 approved these changes

2020-09-22 17:33 UTC, merged